Language.create(name: "Ruby", img_url: "https://img.icons8.com/office/64/000000/ruby-programming-language.png")
Language.create(name: "Javascript", img_url: "https://img.icons8.com/color/64/000000/javascript.png")
Language.create(name: "Python", img_url: "https://img.icons8.com/color/64/000000/python.png")
Language.create(name: "HTML", img_url: "https://img.icons8.com/color/64/000000/html-5.png")
Language.create(name: "SCSS", img_url: "https://img.icons8.com/color/64/000000/css3.png")
Language.create(name: "CSS", img_url: "https://img.icons8.com/color/64/000000/css3.png")
